# fly.toml app configuration file generated for saigely-server-ws on 2025-11-02T13:12:19-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'saigely-server-ws'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 4001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 4001
  processes = ['app']

  [[services.ports]]
    port = 4001

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
